site_name: Arnhem - Wet en Regels
copyright: Deze website is mede mogelijk gemaakt door nick.vm (discord)
# Repository
repo_url: 'https://github.com/nickvmeurs/Arnhem-APV'
repo_name: 'Arnhem-APV'
extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/arnhem
theme:
  language: nl
  name: material
  logo: assets/arnhem.png
  favicon: assets/arnhem.png
  features:
    - header.autohide
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
    
