site_name: Legacy - Wet en Regels
copyright: Deze website is mede mogelijk gemaakt door Raytrix
# Repository
repo_url: 'https://github.com/nickvmeurs/Legacy-APV'
repo_name: 'Legacy-APV'
extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/legacynl
theme:
  language: nl
  name: material
  logo: assets/Legacy.png
  favicon: assets/Legacy.png
  features:
    - header.autohide
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
    
